### ISSUE TITLE
Difficulty interpreting output of QuasiRecomb

### ISSUE THREAD

**Issue by antonkratz** [cbg-ethz/QuasiRecomb#10]
I have difficulty interpreting the output. From determining the coverage I know that "A coverage >10000x is in region 20-10236". I then run QuasiRecomb like this:

```bash
java -jar QuasiRecomb.jar -i xyz.bam -r 20-10236
```

As a result I get a file `quasispecies.fasta` which contains 10,000 apparently unique FASTA sequences. Somehow I was expecting a much lower number of quasispecies (full length viral genome haplotypes) and also information on their respective frequency?! For example with CliqueSNV I get about 10 quasispecies for the same data, with the most frequenct quasispecies contributing about 15%. I understand that these are different algorithms but nevertheless I would have expected something very roughly along these lines.

This is for a viral genome of < 11,000 bases in length, using paired-end Illumina, aligned with bowtie2.

**Comment by armintoepfer** [comment]
Sounds like the model isn't well suited for your data.
