### ISSUE TITLE
QuasiRecomb crashes on large deletion events

### ISSUE THREAD

**Issue by jblamyatifremer** [cbg-ethz/QuasiRecomb#2]
Dear QuasiRecomb creators, 

We ran successfully QuasiRecomb on various parts of our virus's genome (region length from 2000 to 4000 bp). But QuasiRecomb crashes every time that there is a large deletion (>1000 bp) in the targeted regions. We do not understand why...

We use the lastest version of QuasiRecomb on fedora 25 system (with 8 cores + 32 Go Ram). 

## command
java -XX:-UseGCOverheadLimit -XX:+UseParallelGC -XX:+UseNUMA -XX:NewRatio=9 -Xms2G -Xmx10G -jar /export/home/jean-baptiste/Documents/QuasiRecomb.jar -i /export/home/jean-baptiste/Documents/Quasirecomb/new_aln/reads.bam -r 16000-20000 &> log.txt

## the output
00:00:00 Parsing
00:00:00 Parsing		0%
00:00:00 Parsing		1%
[...]
00:00:27 Parsing		99%
00:00:27 Parsing		100%
00:00:27 Parsing		computing
00:50:20 Parsing		           
00:50:20 Parsing		done
00:50:20 Start pairingException in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: java.lang.OutOfMemoryError: Java heap space

I attached the ".bam" file to reproduce the error, the log file (with command and error)  and a screen (from IVG) to see the targeted genomic region with large deletion. 

https://filesender.renater.fr/?s=download&token=88e50855-efc0-dc15-9659-d429b3835ecf

To get all files, please copy/paste this link on your favorite web browser, the download process will start 5 sec after (files will last until 15/05/2017 the servor).

![screenshot_bam_region](https://cloud.githubusercontent.com/assets/13235994/25389154/222afb84-29d0-11e7-9dd3-ce925cbaf842.png)

Cheers, 

JB

**Comment by armintoepfer** [comment]
QuasiRecomb does not respect deletions and thus will not work with regions with coverage 0. There are no plans to support deletions.

**Comment by jblamyatifremer** [comment]
If some users have the same problem... There is no way to get a full length haplotype reconstruction. My strategy was to cut the bam files with region without deletion (run a sequencing depth analysis before) and feed QuasiRecomb. 
It works perfectly.
