### ISSUE TITLE
Quasirecomb - different outputs

### ISSUE THREAD

**Issue by kali1819** [cbg-ethz/QuasiRecomb#4]
Hi, 
I am trying to use QuasiRecomb on my illumina  paried-end data but I experience dome difficulties. I accidentally analyzed the same input file two times and my results were different. I repeated the same command (the same input file) employing -r parameter  several times  and each time I have got different outputs (number of haplotypes). One time QuasiRecomb picked K=1, then K=3 and 5 ect. Even when it picked K=3 two times in a row final results were not the same. 
I performed alignment using InDelFixer as recommended. Alignment looks OK. I've generated sorted and indexed bam file.

Could you please help me to understand my mistake?  I tried to use -noRcomb parameter hoping it will help  but nothing has changed. 
Should I specify K? I thought it is done automatically?
Sorry If this issue sounds trivial, but my experience in this field is limited.

**Comment by armintoepfer** [comment]
Sounds like there is insufficient evidence for a stable pick of K. Either you fix K or add more data.
